# session-init.ps1 - Zero-token session initialization
# Creates/updates .claude-session.md with current state
# Usage: powershell -ExecutionPolicy Bypass -File nexus/scripts/session-init.ps1

param(
    [string]$Task = "Waiting for user direction",
    [switch]$Reset
)

$sessionFile = Join-Path $PSScriptRoot ".." ".." ".claude-session.md"
$progressFile = Join-Path $PSScriptRoot ".." "sprint-progress.json"

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm"

# Get git info
$branch = & git rev-parse --abbrev-ref HEAD 2>$null
$lastCommit = & git log --oneline -1 2>$null
$uncommitted = (& git status --short 2>$null | Measure-Object).Count

# Get fix count dynamically
$fixRegistryFile = Join-Path $PSScriptRoot ".." "FIX_REGISTRY.json"
$fixCount = "?"
if (Test-Path $fixRegistryFile) {
    try {
        $registry = Get-Content $fixRegistryFile -Raw | ConvertFrom-Json
        $fixCount = $registry.fixes.Count
    } catch { }
}

# Get sprint status
$sprintStatus = "No active sprint"
if (Test-Path $progressFile) {
    $progress = Get-Content $progressFile -Raw | ConvertFrom-Json
    if ($progress.status -ne "idle") {
        $sprintStatus = "$($progress.mode) - Loop $($progress.currentLoop)/$($progress.maxLoops) - $($progress.status)"
    }
}

# Build session file
$content = @"
# Claude Session State
**Last Updated:** $timestamp
**Auto-generated by session-init.ps1**

## CURRENT TASK
$Task

## GIT STATE
- Branch: $branch
- Last Commit: $lastCommit
- Uncommitted Files: $uncommitted

## SPRINT STATE
$sprintStatus

## CONTEXT RECOVERY
1. Read this file first after compaction
2. Read nexus/FIX_REGISTRY.json for protected fixes
3. Read nexus/sprint-progress.json for sprint state
4. Read nexus/config/model-modes.json for agent configuration

## CRITICAL FILES
- FIX_REGISTRY.json: $fixCount protected fixes
- WorkflowPreviewCard.tsx: HIGH fix density (NEVER full rewrite)
- sprint-progress.json: Sprint state machine

## NOTES
- System runs in autonomous mode (no permission asking)
- All agents use Agent Output Protocol (max 500 chars inline)
- Model modes configured in nexus/config/model-modes.json
"@

Set-Content -Path $sessionFile -Value $content -Encoding UTF8
Write-Host "Session file updated: $sessionFile" -ForegroundColor Green
Write-Host "Current task: $Task" -ForegroundColor Cyan
