/**
 * KNET (Kuwait National Electronic Payment System) Type Definitions
 *
 * Type definitions for KNET payment integration including:
 * - Payment request/response types
 * - Transaction status codes
 * - Error codes
 * - KWD currency formatting types
 */

// =============================================================================
// TRANSACTION STATUS CONSTANTS
// =============================================================================

/**
 * KNET Transaction Status Codes
 * Based on KNET gateway response codes
 */
export const KNETTransactionStatus = {
  /** Transaction completed successfully */
  CAPTURED: 'CAPTURED',
  /** Transaction is pending/in progress */
  PENDING: 'PENDING',
  /** Transaction was not captured */
  NOT_CAPTURED: 'NOT_CAPTURED',
  /** Transaction was cancelled by user */
  CANCELLED: 'CANCELLED',
  /** Transaction failed */
  FAILED: 'FAILED',
  /** Transaction timed out */
  TIMEOUT: 'TIMEOUT',
  /** Transaction reversed/refunded */
  REVERSED: 'REVERSED',
} as const;

export type KNETTransactionStatusType =
  (typeof KNETTransactionStatus)[keyof typeof KNETTransactionStatus];

// =============================================================================
// ERROR CODES
// =============================================================================

/**
 * KNET Error Codes
 * Common error codes returned by KNET gateway
 */
export const KNETErrorCodes = {
  /** Invalid merchant ID */
  INVALID_MERCHANT: 'E001',
  /** Invalid transaction amount */
  INVALID_AMOUNT: 'E002',
  /** Invalid currency */
  INVALID_CURRENCY: 'E003',
  /** Session expired */
  SESSION_EXPIRED: 'E004',
  /** Duplicate transaction */
  DUPLICATE_TRANSACTION: 'E005',
  /** Card declined */
  CARD_DECLINED: 'E006',
  /** Insufficient funds */
  INSUFFICIENT_FUNDS: 'E007',
  /** Card expired */
  CARD_EXPIRED: 'E008',
  /** Invalid card number */
  INVALID_CARD: 'E009',
  /** Transaction limit exceeded */
  LIMIT_EXCEEDED: 'E010',
  /** System error */
  SYSTEM_ERROR: 'E011',
  /** Network error */
  NETWORK_ERROR: 'E012',
  /** Authentication failed */
  AUTH_FAILED: 'E013',
  /** Invalid signature */
  INVALID_SIGNATURE: 'E014',
  /** Transaction not found */
  TRANSACTION_NOT_FOUND: 'E015',
} as const;

export type KNETErrorCodeType = (typeof KNETErrorCodes)[keyof typeof KNETErrorCodes];

/**
 * KNET Error Code Messages
 * Human-readable messages for error codes
 */
export const KNETErrorMessages: Record<KNETErrorCodeType, string> = {
  [KNETErrorCodes.INVALID_MERCHANT]: 'Invalid merchant configuration',
  [KNETErrorCodes.INVALID_AMOUNT]: 'Invalid transaction amount',
  [KNETErrorCodes.INVALID_CURRENCY]: 'Invalid currency. Only KWD is supported.',
  [KNETErrorCodes.SESSION_EXPIRED]: 'Payment session has expired. Please try again.',
  [KNETErrorCodes.DUPLICATE_TRANSACTION]: 'This transaction has already been processed',
  [KNETErrorCodes.CARD_DECLINED]: 'Your card was declined. Please try a different card.',
  [KNETErrorCodes.INSUFFICIENT_FUNDS]: 'Insufficient funds in your account',
  [KNETErrorCodes.CARD_EXPIRED]: 'Your card has expired',
  [KNETErrorCodes.INVALID_CARD]: 'Invalid card number',
  [KNETErrorCodes.LIMIT_EXCEEDED]: 'Transaction limit exceeded',
  [KNETErrorCodes.SYSTEM_ERROR]: 'A system error occurred. Please try again later.',
  [KNETErrorCodes.NETWORK_ERROR]: 'Network error. Please check your connection.',
  [KNETErrorCodes.AUTH_FAILED]: 'Authentication failed',
  [KNETErrorCodes.INVALID_SIGNATURE]: 'Invalid transaction signature',
  [KNETErrorCodes.TRANSACTION_NOT_FOUND]: 'Transaction not found',
};

// =============================================================================
// PAYMENT REQUEST TYPES
// =============================================================================

/**
 * KNET Payment Request
 * Request payload for initiating a KNET payment
 */
export interface KNETPaymentRequest {
  /** Unique transaction reference (generated by merchant) */
  trackId: string;

  /** Transaction amount in fils (smallest KWD unit, 3 decimal places) */
  amount: number;

  /** Currency code - always KWD for KNET */
  currency: 'KWD';

  /** Language code for payment page */
  language: 'AR' | 'EN';

  /** URL to redirect after successful payment */
  responseUrl: string;

  /** URL to redirect if payment fails or is cancelled */
  errorUrl: string;

  /** User-defined field 1 (optional, passed back in response) */
  udf1?: string;

  /** User-defined field 2 (optional, passed back in response) */
  udf2?: string;

  /** User-defined field 3 (optional, passed back in response) */
  udf3?: string;

  /** User-defined field 4 (optional, passed back in response) */
  udf4?: string;

  /** User-defined field 5 (optional, passed back in response) */
  udf5?: string;

  /** Customer email for receipt */
  customerEmail?: string;

  /** Customer mobile number */
  customerMobile?: string;

  /** Order description */
  description?: string;
}

/**
 * KNET Payment Initialization Response
 * Response from KNET when payment session is created
 */
export interface KNETPaymentInitResponse {
  /** Whether initialization was successful */
  success: boolean;

  /** Payment ID assigned by KNET */
  paymentId?: string;

  /** URL to redirect user to KNET payment page */
  paymentUrl?: string;

  /** Session token for payment */
  sessionToken?: string;

  /** Expiry time for the payment session */
  sessionExpiry?: Date;

  /** Error code if initialization failed */
  errorCode?: KNETErrorCodeType;

  /** Error message if initialization failed */
  errorMessage?: string;
}

// =============================================================================
// PAYMENT RESPONSE TYPES
// =============================================================================

/**
 * KNET Payment Response
 * Response received after payment completion (via callback URL)
 */
export interface KNETPaymentResponse {
  /** Payment ID assigned by KNET */
  paymentId: string;

  /** Merchant's track ID (same as sent in request) */
  trackId: string;

  /** Transaction reference number from KNET */
  transactionId: string;

  /** Reference ID for the transaction */
  referenceId: string;

  /** Transaction result code */
  result: KNETTransactionStatusType;

  /** Authorization code (if successful) */
  authCode?: string;

  /** Transaction amount in fils */
  amount: number;

  /** Currency code */
  currency: 'KWD';

  /** Date and time of transaction */
  transactionDate: Date;

  /** Masked card number (e.g., "****1234") */
  maskedCard?: string;

  /** Card type/brand */
  cardType?: 'KNET' | 'VISA' | 'MASTERCARD';

  /** Post date for the transaction */
  postDate?: Date;

  /** User-defined fields passed back */
  udf1?: string;
  udf2?: string;
  udf3?: string;
  udf4?: string;
  udf5?: string;

  /** Error code if transaction failed */
  errorCode?: KNETErrorCodeType;

  /** Error message if transaction failed */
  errorMessage?: string;

  /** Response signature for verification */
  signature?: string;
}

/**
 * KNET Transaction Details
 * Full transaction details for inquiry/reporting
 */
export interface KNETTransactionDetails {
  /** Payment ID from KNET */
  paymentId: string;

  /** Merchant's track ID */
  trackId: string;

  /** KNET transaction ID */
  transactionId: string;

  /** Reference ID */
  referenceId: string;

  /** Transaction status */
  status: KNETTransactionStatusType;

  /** Transaction amount in fils */
  amount: number;

  /** Currency code */
  currency: 'KWD';

  /** Authorization code */
  authCode?: string;

  /** Transaction timestamp */
  transactionDate: Date;

  /** Post date */
  postDate?: Date;

  /** Masked card number */
  maskedCard?: string;

  /** Card type */
  cardType?: 'KNET' | 'VISA' | 'MASTERCARD';

  /** Whether transaction can be reversed/refunded */
  canReverse: boolean;

  /** Reversal amount if partially reversed */
  reversedAmount?: number;

  /** Original amount before any reversals */
  originalAmount: number;

  /** Customer email */
  customerEmail?: string;

  /** Customer mobile */
  customerMobile?: string;

  /** Transaction description */
  description?: string;

  /** Metadata from user-defined fields */
  metadata?: Record<string, string>;

  /** Created timestamp in our system */
  createdAt: Date;

  /** Last updated timestamp */
  updatedAt: Date;
}

// =============================================================================
// CURRENCY TYPES
// =============================================================================

/**
 * KWD Amount
 * Represents an amount in Kuwaiti Dinar
 * Note: KWD has 3 decimal places (1 KWD = 1000 fils)
 */
export interface KWDAmount {
  /** Amount in fils (smallest unit) */
  fils: number;

  /** Amount in KWD (for display) */
  kwd: number;

  /** Formatted string representation */
  formatted: string;
}

/**
 * KWD Formatting Options
 */
export interface KWDFormatOptions {
  /** Whether to include currency symbol */
  includeSymbol?: boolean;

  /** Whether to include currency code */
  includeCurrencyCode?: boolean;

  /** Locale for number formatting */
  locale?: 'en-KW' | 'ar-KW';

  /** Number of decimal places (default: 3) */
  decimals?: number;
}

// =============================================================================
// VERIFICATION TYPES
// =============================================================================

/**
 * KNET Verification Request
 * Request to verify a payment
 */
export interface KNETVerificationRequest {
  /** Payment ID to verify */
  paymentId: string;

  /** Track ID for reference */
  trackId: string;
}

/**
 * KNET Verification Response
 */
export interface KNETVerificationResponse {
  /** Whether verification was successful */
  verified: boolean;

  /** Transaction details if verified */
  transaction?: KNETTransactionDetails;

  /** Error code if verification failed */
  errorCode?: KNETErrorCodeType;

  /** Error message if verification failed */
  errorMessage?: string;
}

// =============================================================================
// REFUND TYPES
// =============================================================================

/**
 * KNET Refund Request
 */
export interface KNETRefundRequest {
  /** Original payment ID */
  paymentId: string;

  /** Original transaction ID */
  transactionId: string;

  /** Refund amount in fils (must be <= original amount) */
  amount: number;

  /** Reason for refund */
  reason?: string;
}

/**
 * KNET Refund Response
 */
export interface KNETRefundResponse {
  /** Whether refund was successful */
  success: boolean;

  /** Refund transaction ID */
  refundTransactionId?: string;

  /** Refund reference ID */
  refundReferenceId?: string;

  /** Amount refunded in fils */
  refundedAmount?: number;

  /** Remaining amount on original transaction */
  remainingAmount?: number;

  /** Refund status */
  status?: 'PENDING' | 'COMPLETED' | 'FAILED';

  /** Error code if refund failed */
  errorCode?: KNETErrorCodeType;

  /** Error message if refund failed */
  errorMessage?: string;
}

// =============================================================================
// CALLBACK TYPES
// =============================================================================

/**
 * KNET Callback Data
 * Data received at callback URL after payment
 */
export interface KNETCallbackData {
  /** Raw query parameters from callback */
  rawParams: Record<string, string>;

  /** Parsed payment response */
  paymentResponse: KNETPaymentResponse;

  /** Whether signature is valid */
  signatureValid: boolean;

  /** Callback timestamp */
  receivedAt: Date;
}

// =============================================================================
// UI STATE TYPES
// =============================================================================

/**
 * KNET Payment State
 * State for tracking payment flow in UI
 */
export interface KNETPaymentState {
  /** Current step in payment flow */
  step: 'idle' | 'initializing' | 'redirecting' | 'processing' | 'completed' | 'failed';

  /** Payment session data */
  session?: {
    paymentId: string;
    paymentUrl: string;
    sessionToken: string;
    expiresAt: Date;
  };

  /** Transaction result */
  result?: KNETPaymentResponse;

  /** Error information */
  error?: {
    code: KNETErrorCodeType;
    message: string;
  };

  /** Loading state */
  isLoading: boolean;
}

/**
 * KNET Payment Button Props
 */
export interface KNETPaymentButtonProps {
  /** Amount to charge in fils */
  amount: number;

  /** Track ID for the transaction */
  trackId?: string;

  /** Order description */
  description?: string;

  /** Customer email */
  customerEmail?: string;

  /** Customer mobile */
  customerMobile?: string;

  /** Callback when payment succeeds */
  onSuccess?: (response: KNETPaymentResponse) => void;

  /** Callback when payment fails */
  onError?: (error: { code: KNETErrorCodeType; message: string }) => void;

  /** Callback when payment is cancelled */
  onCancel?: () => void;

  /** Whether button is disabled */
  disabled?: boolean;

  /** Custom button text */
  buttonText?: string;

  /** Additional CSS classes */
  className?: string;
}

/**
 * KNET Payment Form Props
 */
export interface KNETPaymentFormProps {
  /** Amount to charge in fils */
  amount: number;

  /** Order description */
  description?: string;

  /** Product/service name */
  productName?: string;

  /** Customer email (pre-filled if available) */
  customerEmail?: string;

  /** Customer mobile (pre-filled if available) */
  customerMobile?: string;

  /** Callback when payment succeeds */
  onSuccess?: (response: KNETPaymentResponse) => void;

  /** Callback when payment fails */
  onError?: (error: { code: KNETErrorCodeType; message: string }) => void;

  /** Callback when user cancels */
  onCancel?: () => void;

  /** Whether form is in loading state */
  isLoading?: boolean;

  /** Language for the form */
  language?: 'AR' | 'EN';
}
